### ISSUE TITLE
Do control-controls support "Consolidated control findings"?

### ISSUE THREAD

**Issue by htnosm** [pepabo/control-controls#34]
Thanks for this useful software.
Do control-controls support "Consolidated control findings"?

ref. [Impact of consolidation on ASFF fields and values \- AWS Security Hub](https://docs.aws.amazon.com/securityhub/latest/userguide/asff-changes-consolidation.html)

In an environment where Consolidated control findings are "On",
`ProductFields.StandardsArn` is removed and replaced with `Compliance.AssociatedStandards`.
This is probably why `standards.<standard>.findings.<control_id>.<target_arn>.status` and `note` doesn't work.
e.g. https://github.com/pepabo/control-controls/blob/main/sechub/plan.go#L168

**Comment by k1LoW** [comment]
@htnosm Thank you for your contribution!

control-controls does not support Consolidated control findings. Also, I do not have any knowledge about it.
Sorry, please wait for a while.
